### ISSUE TITLE
Hosting Files Created via Python & AASXPE (24_2_27) using Server Blazor 2023_09_13 not working

### ISSUE THREAD

**Issue by NLIFTTUW** [eclipse-aaspe/server#269]
### Describe the bug

Starting REST Server with demo files (possibly created in an earlier version of AASXPE) is possible.

![Errorreport_clean_ServerBlazor](https://github.com/eclipse-aaspe/server/assets/171046877/f42226db-c66f-4972-bf67-6d5b40196d3d)

Starting REST Server with my own files is not possible (tried different approaches to see if the files are corrupted / Files checked via Certification Portal)- See Powershell

![Errorreport_ServerBlazor](https://github.com/eclipse-aaspe/server/assets/171046877/47ffa00c-9714-483a-8cb8-97bc0e46bb3f)

![AAS_Certification_portal_test_positive](https://github.com/eclipse-aaspe/server/assets/171046877/8d741c5b-9f0f-4bc8-88ba-dbe53c0e69d6)

### To reproduce

Steps to reproduce the behaviour.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Relevant log output

```shell
PS C:\Users\User\AASX Package Explorer\AasxServerBlazor.2023-09-13.alpha\AasxServerBlazor> .\startForDemo.bat

C:\Users\User\AASX Package Explorer\AasxServerBlazor.2023-09-13.alpha\AasxServerBlazor>AasxServerBlazor.exe --rest --no-security --data-path aasxs
C:\Users\User\AASX Package Explorer\AasxServerBlazor.2023-09-13.alpha\AasxServerBlazor
2024-06-11 16:01:04 warn: Microsoft.AspNetCore.Server.Kestrel[0] Overriding address(es) 'http://*:5000'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
Serving the AASXs from: aasxs
Security 1 Startup - Server
Security 1.1 Load X509 Root Certificates into X509 Store Root
Loading aasxs\ArduinoUNO.aasx...
ValueType  not found for property SimulatorApplicability
ValueType  not found for property SimulatorApplicability
Loading aasxs\Composite.aasx...
ValueType  not found for property TypClass
ValueType  not found for property ChargeId
Loading aasxs\DCmotor.aasx...
Loading aasxs\Example_AAS_ServoDCMotor_21.aasx...
ValueType langString not found for property ProductDesignation
ValueType langString not found for property DocumentClassName
ValueType langString not found for property Title
Loading aasxs\LED1.aasx...
Loading aasxs\LED2.aasx...
Loading aasxs\TemperatureSensor.aasx...
ValueType  not found for property Temperature
Loading aasxs\wfl_machine_asset_2024-06-11_15-52-59.aasx...
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: While reading the aasxs\wfl_machine_asset_2024-06-11_15-52-59.aasx (and indirectly over C:\Users\User\AppData\Local\Temp\tmp629D.aasx) at \AdminShellPackageEnv.cs:line 389 gave: Unable to find AASX origin. Aborting!
   at AdminShellNS.AdminShellPackageEnv.LoadPackageAasx(String fn, String fnToLoad) in D:\a\aasx-server\aasx-server\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:line 450
   at AdminShellNS.AdminShellPackageEnv.Load(String fn, Boolean indirectLoadSave) in D:\a\aasx-server\aasx-server\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:line 511
   at AdminShellNS.AdminShellPackageEnv..ctor(String fn, Boolean indirectLoadSave) in D:\a\aasx-server\aasx-server\src\AasxCsharpLibrary\AdminShellPackageEnv.cs:line 272
   at AasxServer.Program.Run(CommandLineArguments a) in D:\a\aasx-server\aasx-server\src\AasxServerStandardBib\Program.cs:line 479
   at AasxServer.Program.<>c.<Main>b__44_0(CommandLineArguments a) in D:\a\aasx-server\aasx-server\src\AasxServerStandardBib\Program.cs:line 840
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Delegate.DynamicInvoke(Object[] args)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
PS C:\Users\User\AASX Package Explorer\AasxServerBlazor.2023-09-13.alpha\AasxServerBlazor> .\startForDemo.bat

C:\Users\User\AASX Package Explorer\AasxServerBlazor.2023-09-13.alpha\AasxServerBlazor>AasxServerBlazor.exe --rest --no-security --data-path aasxs
C:\Users\User\AASX Package Explorer\AasxServerBlazor.2023-09-13.alpha\AasxServerBlazor
2024-06-11 16:04:38 warn: Microsoft.AspNetCore.Server.Kestrel[0] Overriding address(es) 'http://*:5000'. Binding to endpoints defined via IConfiguration and/or UseKestrel() instead.
Serving the AASXs from: aasxs
Security 1 Startup - Server
Security 1.1 Load X509 Root Certificates into X509 Store Root
Loading aasxs\ArduinoUNO.aasx...
ValueType  not found for property SimulatorApplicability
ValueType  not found for property SimulatorApplicability
Loading aasxs\Composite.aasx...
ValueType  not found for property TypClass
ValueType  not found for property ChargeId
Loading aasxs\DCmotor.aasx...
Loading aasxs\Example_AAS_ServoDCMotor_21.aasx...
ValueType langString not found for property ProductDesignation
ValueType langString not found for property DocumentClassName
ValueType langString not found for property Title
Loading aasxs\LED1.aasx...
Loading aasxs\LED2.aasx...
Loading aasxs\TemperatureSensor.aasx...
ValueType  not found for property Temperature

Please wait for the servers to start...
Connect to REST by: localhost:51310
http://localhost:51310/
REST Server started.
Servers successfully started. Press Ctrl-C to exit...
Registry is empty
```

**Comment by Freezor** [comment]
Hi @NLIFTTUW could you provide the aasx file you were trying to open?

**Comment by NLIFTTUW** [comment]
Here are 2 of my files i created. Both wont load on the server

[AASX.zip](https://github.com/user-attachments/files/15802878/AASX.zip)
